import 'dart:math' as math;

// Index order is the firmware PatternId enum, not the former UI mock order.
enum PatternId { simple, teasing, robo, half, deeper, stopGo, insist }

class StrokePattern {
  const StrokePattern({
    required this.id,
    required this.name,
    required this.hint,
  });
  final PatternId id;
  final String name, hint;
  bool get isCustom => false;
  // Illustrative thumbnail only; actual motion is generated by firmware.
  double sample(double t) {
    final phase = (t * 3) % 1;
    final wave = .5 - .5 * math.cos(phase * math.pi * 2);
    return switch (id) {
      PatternId.simple => .15 + .7 * wave,
      PatternId.teasing => .15 + .7 * math.pow(wave, 2).toDouble(),
      PatternId.robo => phase < .5 ? .15 + 1.4 * phase : 1.55 - 1.4 * phase,
      PatternId.half => .15 + ((t * 3).floor().isEven ? .7 : .35) * wave,
      PatternId.deeper => .15 + (.2 + .25 * (t * 3).floor().clamp(0, 2)) * wave,
      PatternId.stopGo =>
        phase < .25
            ? .15
            : .15 +
                  .7 * (.5 - .5 * math.cos((phase - .25) / .75 * math.pi * 2)),
      PatternId.insist => .15 + .25 * wave,
    };
  }

  static const catalog = [
    StrokePattern(
      id: PatternId.simple,
      name: '匀速',
      hint: 'Simple Stroke · 平稳往复',
    ),
    StrokePattern(
      id: PatternId.teasing,
      name: '挑逗',
      hint: 'Teasing or Pounding · 由手感参数调节进出节奏',
    ),
    StrokePattern(id: PatternId.robo, name: '机械', hint: 'Robo Stroke · 鲜明节奏'),
    StrokePattern(id: PatternId.half, name: '交错', hint: "Half’n’Half · 深浅交替"),
    StrokePattern(id: PatternId.deeper, name: '渐深', hint: 'Deeper · 逐步加深'),
    StrokePattern(id: PatternId.stopGo, name: '停顿', hint: "Stop’n’Go · 往复与停顿"),
    StrokePattern(id: PatternId.insist, name: '短促', hint: 'Insist · 局部短行程'),
  ];
}
