import 'dart:math' as math;

// Index order is the firmware PatternId enum, not the former UI mock order.
enum PatternId { simple, teasing, robo, half, deeper, stopGo, insist }

/// What the firmware does with `sensation` for one pattern.
/// Firmware maps sensation 0..100 to s = (sensation − 50) × 2 ∈ [−100, 100].
class SensationSpec {
  const SensationSpec({
    required this.title,
    required this.low,
    required this.mid,
    required this.high,
    this.enabled = true,
  });
  final String title, low, mid, high;
  final bool enabled;
}

class StrokePattern {
  const StrokePattern({
    required this.id,
    required this.name,
    required this.english,
    required this.hint,
    required this.sensation,
  });
  final PatternId id;
  final String name, english, hint;
  final SensationSpec sensation;

  /// Human readout of the current sensation, mirroring Patterns.cpp.
  String readout(double value) {
    final s = (value - 50) * 2;
    final a = s.abs();
    return switch (id) {
      PatternId.robo => '—',
      PatternId.simple || PatternId.half =>
        s.round() == 0 ? '进出等速' : '${s > 0 ? '入' : '出'} ${(50 + a * .35).round()}% 快',
      PatternId.teasing =>
        s.round() == 0 ? '居中' : '${s > 0 ? '猛插' : '猛抽'} ×${(1 + a / 100 * 4).toStringAsFixed(1)}',
      PatternId.deeper =>
        '${(s < 0 ? 11 + s / 100 * 9 : 11 + s / 100 * 21).round().clamp(2, 32)} 次到底',
      PatternId.stopGo => '停 ${(80 + a / 100 * 520).round()} ms',
      PatternId.insist => a < 1
          ? '全程'
          : '${s > 0 ? '深处' : '浅处'} ${math.max(8, 100 - a).round()}%',
    };
  }

  // Illustrative thumbnail only; actual motion is generated by firmware.
  double sample(double t) {
    final phase = (t * 3) % 1;
    final wave = .5 - .5 * math.cos(phase * math.pi * 2);
    return switch (id) {
      PatternId.simple => .15 + .7 * wave,
      PatternId.teasing => .15 + .7 * math.pow(wave, 2).toDouble(),
      PatternId.robo => phase < .5 ? .15 + 1.4 * phase : 1.55 - 1.4 * phase,
      PatternId.half => .15 + ((t * 3).floor().isEven ? .35 : .7) * wave,
      PatternId.deeper => .15 + (.25 + .225 * (t * 3).floor().clamp(0, 2)) * wave,
      PatternId.stopGo =>
        phase < .25
            ? .15
            : .15 +
                  .7 * (.5 - .5 * math.cos((phase - .25) / .75 * math.pi * 2)),
      PatternId.insist => .6 + .25 * wave,
    };
  }

  static const _rhythm = SensationSpec(
    title: '进出节奏',
    low: '抽出更快',
    mid: '等速',
    high: '插入更快',
  );

  static const catalog = [
    StrokePattern(
      id: PatternId.simple,
      name: '匀速',
      english: 'Simple Stroke',
      hint: '在起点和最深点之间平稳往复',
      sensation: _rhythm,
    ),
    StrokePattern(
      id: PatternId.teasing,
      name: '挑逗',
      english: 'Teasing or Pounding',
      hint: '一侧快一侧慢，越偏离中间反差越大',
      sensation: SensationSpec(
        title: '反差方向',
        low: '猛抽慢插',
        mid: '柔和',
        high: '猛插慢抽',
      ),
    ),
    StrokePattern(
      id: PatternId.robo,
      name: '机械',
      english: 'Robo Stroke',
      hint: '固定 50/50 节奏，不受手感影响',
      sensation: SensationSpec(
        title: '手感',
        low: '',
        mid: '此模式节奏固定',
        high: '',
        enabled: false,
      ),
    ),
    StrokePattern(
      id: PatternId.half,
      name: '深浅',
      english: "Half'n'Half",
      hint: '半程与全程交替',
      sensation: _rhythm,
    ),
    StrokePattern(
      id: PatternId.deeper,
      name: '渐深',
      english: 'Deeper',
      hint: '每一下更深一点，到底后重新开始',
      sensation: SensationSpec(
        title: '加深周期',
        low: '2 次',
        mid: '11 次',
        high: '32 次',
      ),
    ),
    StrokePattern(
      id: PatternId.stopGo,
      name: '停顿',
      english: "Stop'n'Go",
      hint: '插入、停住、抽出、停住',
      sensation: SensationSpec(
        title: '停顿时长',
        low: '长',
        mid: '短 80 ms',
        high: '长',
      ),
    ),
    StrokePattern(
      id: PatternId.insist,
      name: '短促',
      english: 'Insist',
      hint: '在一端做短行程快速往复',
      sensation: SensationSpec(
        title: '集中位置',
        low: '浅处短冲',
        mid: '完整行程',
        high: '深处短冲',
      ),
    ),
  ];
}
